package de.dylogix.skywars.listener;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Random;

import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.Sound;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.block.Action;
import org.bukkit.event.inventory.InventoryCloseEvent;
import org.bukkit.event.player.PlayerInteractEvent;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.InventoryHolder;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.inventory.meta.PotionMeta;
import org.bukkit.potion.PotionData;
import org.bukkit.potion.PotionType;

import de.dylogix.skywars.enums.GameState;
import de.dylogix.skywars.main.Main;

public class ChestListener implements Listener{	
	public static HashMap<Location, Inventory> chests = new HashMap<Location, Inventory>();
	public static HashMap<Location, Inventory> epicchests = new HashMap<Location, Inventory>();
	public static HashMap<Player, Integer> openchests = new HashMap<Player, Integer>();
	private ArrayList<ItemStack> loot = new ArrayList<ItemStack>();
	private ArrayList<ItemStack> epicloot = new ArrayList<ItemStack>();
    
    public int rndInt(int min, int max) {
        Random r = new Random();
        int i = r.nextInt(max - min + 1) + min;
        return i;
    }
    
	public static ItemStack create(Material mat, int amount) {
        return new ItemStack(mat, amount);
    }
	
	public ItemStack createPotion(Material mat, PotionType pt, int amount, Boolean arg, Boolean arg2) {
		ItemStack potion = new ItemStack(mat, amount);
    	PotionMeta meta = (PotionMeta) potion.getItemMeta();
    	meta.setBasePotionData(new PotionData(pt, arg, arg2));
    	potion.setItemMeta(meta);
    	
    	return potion;
	}
	
	public ItemStack createEnchanted(Material mat, Enchantment ench, int level) {
    	ItemStack item = new ItemStack(mat);
    	ItemMeta meta = item.getItemMeta();
    	meta.addEnchant(ench, level, true);
    	item.setItemMeta(meta);
		
    	return item;
	}
	
	@EventHandler 
	public void onChestClose(InventoryCloseEvent e) {
		Player p = (Player) e.getPlayer();
		if(e.getView().getTitle().equals("§2Normal Chest") || e.getView().getTitle().equals("§5Epic Chest")) {
			p.playSound(p, Sound.BLOCK_CHEST_CLOSE, 1, 1);
		}
	}
	
    @EventHandler
    public void onChestOpen(PlayerInteractEvent e) {
    	try{
	    	if(Main.gs == GameState.INGAME){
	    		if (e.getAction() == Action.RIGHT_CLICK_BLOCK && e.getClickedBlock().getType() == Material.CHEST){
		        	e.setCancelled(true);
		        	if(!Main.alive.contains(e.getPlayer())){
		        		return;
		        	}
		        	if (!ChestListener.chests.containsKey((Object)e.getClickedBlock().getLocation())) {
		                this.registerLoot();
		                
		                openchests.put(e.getPlayer(), openchests.get(e.getPlayer()) + 1);
		
		                Inventory inv = Bukkit.createInventory((InventoryHolder)null, (int)27, (String)"§2Normal Chest");
		                int i = 0;
		                while (i < rndInt(15, 22)) {
		                    inv.setItem(rndInt(0, inv.getSize() - 1), this.loot.get(rndInt(0, this.loot.size() - 1)));
		                    ++i;
		                }
		                ChestListener.chests.put(e.getClickedBlock().getLocation(), inv);
		            }
		        	e.getPlayer().openInventory(ChestListener.chests.get((Object)e.getClickedBlock().getLocation()));
		        	e.getPlayer().playSound(e.getPlayer(), Sound.BLOCK_CHEST_OPEN, 1, 1);
		        } else if(e.getAction() == Action.RIGHT_CLICK_BLOCK && e.getClickedBlock().getType() == Material.TRAPPED_CHEST){
		        	e.setCancelled(true);
		        	if(!Main.alive.contains(e.getPlayer())){
		        		return;
		        	}
		        	if (!ChestListener.chests.containsKey((Object)e.getClickedBlock().getLocation())) {
		                this.registerEpicLoot();
		                
		                openchests.put(e.getPlayer(), openchests.get(e.getPlayer()) + 1);
		                Inventory inv = Bukkit.createInventory((InventoryHolder)null, (int)27, (String)"§5Epic Chest");
		                int i = 0;
		                while (i < rndInt(15, 22)) {
		                    inv.setItem(rndInt(0, inv.getSize() - 1), this.epicloot.get(rndInt(0, this.epicloot.size() - 1)));
		                    ++i;
		                }
		                ChestListener.chests.put(e.getClickedBlock().getLocation(), inv);
		            }
		            e.getPlayer().openInventory(ChestListener.chests.get((Object)e.getClickedBlock().getLocation()));
		        	e.getPlayer().playSound(e.getPlayer(), Sound.BLOCK_CHEST_OPEN, 1, 1);
		        }
	    	}
	    }catch(Exception e1){ e1.printStackTrace(); }
    }
    
    public void registerLoot() {
    	// enchanted items
    	this.loot.add(createEnchanted(Material.WOODEN_SWORD, Enchantment.DAMAGE_ALL, 1));
    	this.loot.add(createEnchanted(Material.WOODEN_SWORD, Enchantment.DAMAGE_ALL, 1));
    	this.loot.add(createEnchanted(Material.WOODEN_SWORD, Enchantment.DAMAGE_ALL, 1));
    	this.loot.add(createEnchanted(Material.WOODEN_SWORD, Enchantment.DAMAGE_ALL, 1));
    	this.loot.add(createEnchanted(Material.WOODEN_SWORD, Enchantment.DAMAGE_ALL, 1));
    	this.loot.add(createEnchanted(Material.STONE_SWORD, Enchantment.DAMAGE_ALL, 1));
    	this.loot.add(createEnchanted(Material.IRON_SWORD, Enchantment.DAMAGE_ALL, 1));
    	this.loot.add(createEnchanted(Material.CHAINMAIL_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.CHAINMAIL_CHESTPLATE, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.CHAINMAIL_LEGGINGS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.CHAINMAIL_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.IRON_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.IRON_CHESTPLATE, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.IRON_LEGGINGS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.IRON_BOOTS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.CHAINMAIL_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.CHAINMAIL_CHESTPLATE, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.CHAINMAIL_LEGGINGS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.CHAINMAIL_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.IRON_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.IRON_CHESTPLATE, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.IRON_LEGGINGS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.IRON_BOOTS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.CHAINMAIL_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.CHAINMAIL_CHESTPLATE, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.CHAINMAIL_LEGGINGS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.CHAINMAIL_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.IRON_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.IRON_CHESTPLATE, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.IRON_LEGGINGS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.IRON_BOOTS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.CHAINMAIL_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.CHAINMAIL_CHESTPLATE, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.CHAINMAIL_LEGGINGS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.CHAINMAIL_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.WOODEN_SWORD, Enchantment.DAMAGE_ALL, 1));
    	this.loot.add(createEnchanted(Material.WOODEN_SWORD, Enchantment.DAMAGE_ALL, 1));
    	this.loot.add(createEnchanted(Material.STONE_SWORD, Enchantment.DAMAGE_ALL, 1));
    	this.loot.add(createEnchanted(Material.IRON_SWORD, Enchantment.DAMAGE_ALL, 1));
    	this.loot.add(createEnchanted(Material.WOODEN_SWORD, Enchantment.DAMAGE_ALL, 1));
    	this.loot.add(createEnchanted(Material.IRON_SWORD, Enchantment.DAMAGE_ALL, 1));
    	this.loot.add(createEnchanted(Material.IRON_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.IRON_CHESTPLATE, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.IRON_LEGGINGS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.IRON_BOOTS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.loot.add(createEnchanted(Material.WOODEN_SWORD, Enchantment.DAMAGE_ALL, 1));
    	this.loot.add(createEnchanted(Material.STONE_SWORD, Enchantment.DAMAGE_ALL, 1));
    	this.loot.add(createEnchanted(Material.WOODEN_SWORD, Enchantment.DAMAGE_ALL, 1));
    	this.loot.add(createEnchanted(Material.STONE_SWORD, Enchantment.DAMAGE_ALL, 1));
    	this.loot.add(createEnchanted(Material.IRON_SWORD, Enchantment.DAMAGE_ALL, 1));
        
    	// potions
    	this.loot.add(createPotion(Material.SPLASH_POTION, PotionType.REGEN, 1, false, true));
    	this.loot.add(createPotion(Material.SPLASH_POTION, PotionType.INSTANT_HEAL, 1, false, true));
    	this.loot.add(createPotion(Material.SPLASH_POTION, PotionType.SLOWNESS, 1, false, false));
    	this.loot.add(createPotion(Material.SPLASH_POTION, PotionType.WEAKNESS, 1, false, false));
    	this.loot.add(createPotion(Material.SPLASH_POTION, PotionType.POISON, 1, false, false));
    	this.loot.add(createPotion(Material.SPLASH_POTION, PotionType.REGEN, 1, false, true));
    	
    	// regular items
        this.loot.add(create(Material.WOODEN_SWORD, 1));
        this.loot.add(create(Material.APPLE, rndInt(1, 4)));
        this.loot.add(create(Material.IRON_HELMET, 1));
        this.loot.add(create(Material.IRON_CHESTPLATE, 1));
        this.loot.add(create(Material.BAKED_POTATO, rndInt(1, 5)));
        this.loot.add(create(Material.GOLDEN_APPLE, 1));
        this.loot.add(create(Material.STONE_SWORD, 1));
        this.loot.add(create(Material.FISHING_ROD, 1));
        this.loot.add(create(Material.EXPERIENCE_BOTTLE, rndInt(1, 4)));
        this.loot.add(create(Material.DIAMOND_CHESTPLATE, 1));
        this.loot.add(create(Material.DIAMOND, rndInt(1, 8)));
        this.loot.add(create(Material.DIAMOND, rndInt(1, 8)));
        this.loot.add(create(Material.IRON_INGOT, rndInt(1, 8)));
        this.loot.add(create(Material.IRON_INGOT, rndInt(1, 8)));
        this.loot.add(create(Material.IRON_INGOT, rndInt(1, 8)));
        this.loot.add(create(Material.GOLD_INGOT, rndInt(1, 8)));
        this.loot.add(create(Material.GOLD_INGOT, rndInt(1, 8)));
        this.loot.add(create(Material.GOLD_INGOT, rndInt(1, 8)));
        this.loot.add(create(Material.GOLD_INGOT, rndInt(1, 8)));
        this.loot.add(create(Material.BAKED_POTATO, rndInt(1, 5)));
        this.loot.add(create(Material.MELON, rndInt(1, 5)));
        this.loot.add(create(Material.TNT, rndInt(1, 8)));
        this.loot.add(create(Material.TNT, rndInt(1, 8)));
        this.loot.add(create(Material.TNT, rndInt(1, 8)));
        this.loot.add(create(Material.TNT, rndInt(1, 8)));
        this.loot.add(create(Material.TNT, rndInt(1, 8)));
        this.loot.add(create(Material.FLINT_AND_STEEL, rndInt(1, 1)));
        this.loot.add(create(Material.TNT, rndInt(1, 8)));
        this.loot.add(create(Material.FLINT_AND_STEEL, rndInt(1, 1)));
        this.loot.add(create(Material.FLINT_AND_STEEL, rndInt(1, 1)));
        this.loot.add(create(Material.FLINT_AND_STEEL, rndInt(1, 1)));
        this.loot.add(create(Material.IRON_LEGGINGS, 1));
        this.loot.add(create(Material.APPLE, rndInt(1, 4)));
        this.loot.add(create(Material.IRON_BOOTS, 1));
        this.loot.add(create(Material.COOKED_CHICKEN, rndInt(1, 5)));
        this.loot.add(create(Material.COOKED_BEEF, rndInt(1, 5)));
        this.loot.add(create(Material.GOLDEN_BOOTS, 1));
        this.loot.add(create(Material.IRON_SWORD, 1));
        this.loot.add(create(Material.APPLE, rndInt(1, 4)));
        this.loot.add(create(Material.IRON_HELMET, 1));
        this.loot.add(create(Material.GOLDEN_CHESTPLATE, 1));
        this.loot.add(create(Material.BAKED_POTATO, rndInt(1, 5)));
        this.loot.add(create(Material.BAKED_POTATO, rndInt(1, 5)));
        this.loot.add(create(Material.CHAINMAIL_LEGGINGS, 1));
        this.loot.add(create(Material.EXPERIENCE_BOTTLE, rndInt(1, 4)));
        this.loot.add(create(Material.MELON, rndInt(1, 5)));
        this.loot.add(create(Material.APPLE, rndInt(1, 4)));
        this.loot.add(create(Material.COOKED_CHICKEN, rndInt(1, 5)));
        this.loot.add(create(Material.CHAINMAIL_LEGGINGS, 1));
        this.loot.add(create(Material.COOKED_BEEF, rndInt(1, 5)));
        this.loot.add(create(Material.IRON_SWORD, 1));
        this.loot.add(create(Material.FISHING_ROD, 1));
        this.loot.add(create(Material.CHAINMAIL_HELMET, 1));
        this.loot.add(create(Material.APPLE, rndInt(1, 4)));
        this.loot.add(create(Material.IRON_HELMET, 1));
        this.loot.add(create(Material.GOLDEN_CHESTPLATE, 1));
        this.loot.add(create(Material.STONE_AXE, 1));
        this.loot.add(create(Material.IRON_CHESTPLATE, 1));
        this.loot.add(create(Material.BAKED_POTATO, rndInt(1, 5)));
        this.loot.add(create(Material.IRON_SWORD, 1));
        this.loot.add(create(Material.CHAINMAIL_BOOTS, 1));
        this.loot.add(create(Material.EXPERIENCE_BOTTLE, rndInt(1, 4)));
        this.loot.add(create(Material.BAKED_POTATO, rndInt(1, 5)));
        this.loot.add(create(Material.STONE, rndInt(1, 64)));
        this.loot.add(create(Material.COBBLESTONE, rndInt(1, 64)));
        this.loot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.loot.add(create(Material.OAK_PLANKS, rndInt(1, 64)));
        this.loot.add(create(Material.BRICK, rndInt(1, 64)));
        this.loot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.loot.add(create(Material.STONE_SWORD, 1));
        this.loot.add(create(Material.MELON, rndInt(1, 5)));
        this.loot.add(create(Material.IRON_LEGGINGS, 1));
        this.loot.add(create(Material.APPLE, rndInt(1, 4)));
        this.loot.add(create(Material.IRON_BOOTS, 1));
        this.loot.add(create(Material.DIAMOND_CHESTPLATE, 1));
        this.loot.add(create(Material.COOKED_CHICKEN, rndInt(1, 5)));
        this.loot.add(create(Material.CHAINMAIL_LEGGINGS, 1));
        this.loot.add(create(Material.COOKED_BEEF, rndInt(1, 5)));
        this.loot.add(create(Material.GOLDEN_BOOTS, 1));
        this.loot.add(create(Material.IRON_SWORD, 1));
        this.loot.add(create(Material.APPLE, rndInt(1, 4)));
        this.loot.add(create(Material.IRON_HELMET, 1));
        this.loot.add(create(Material.GOLDEN_CHESTPLATE, 1));
        this.loot.add(create(Material.IRON_CHESTPLATE, 1));
        this.loot.add(create(Material.BAKED_POTATO, rndInt(1, 5)));
        this.loot.add(create(Material.GOLDEN_APPLE, 1));
        this.loot.add(create(Material.CHAINMAIL_BOOTS, 1));
        this.loot.add(create(Material.STONE_SWORD, 1));
        this.loot.add(create(Material.COBWEB, rndInt(1, 4)));
        this.loot.add(create(Material.EXPERIENCE_BOTTLE, rndInt(1, 4)));
        this.loot.add(create(Material.BAKED_POTATO, rndInt(1, 5)));
        this.loot.add(create(Material.CHAINMAIL_LEGGINGS, 1));
        this.loot.add(create(Material.MELON, rndInt(1, 5)));
        this.loot.add(create(Material.APPLE, rndInt(1, 4)));
        this.loot.add(create(Material.COOKED_CHICKEN, rndInt(1, 5)));
        this.loot.add(create(Material.CHAINMAIL_LEGGINGS, 1));
        this.loot.add(create(Material.COOKED_BEEF, rndInt(1, 5)));
        this.loot.add(create(Material.GOLDEN_BOOTS, 1));
        this.loot.add(create(Material.CHAINMAIL_HELMET, 1));
        this.loot.add(create(Material.APPLE, rndInt(1, 4)));
        this.loot.add(create(Material.GOLDEN_CHESTPLATE, 1));
        this.loot.add(create(Material.STONE_SWORD, 1));
        this.loot.add(create(Material.STONE_AXE, 1));
        this.loot.add(create(Material.FISHING_ROD, 1));
        this.loot.add(create(Material.IRON_CHESTPLATE, 1));
        this.loot.add(create(Material.BAKED_POTATO, rndInt(1, 5)));
        this.loot.add(create(Material.GOLDEN_APPLE, 1));
        this.loot.add(create(Material.STICK, rndInt(1, 3)));
        this.loot.add(create(Material.BAKED_POTATO, rndInt(1, 5)));
        this.loot.add(create(Material.CHAINMAIL_LEGGINGS, 1));
        this.loot.add(create(Material.MELON, rndInt(1, 5)));
        this.loot.add(create(Material.IRON_LEGGINGS, 1));
        this.loot.add(create(Material.GOLDEN_PICKAXE, 1));
        this.loot.add(create(Material.GOLDEN_PICKAXE, 1));
        this.loot.add(create(Material.GOLDEN_PICKAXE, 1));
        this.loot.add(create(Material.IRON_PICKAXE, 1));
        this.loot.add(create(Material.IRON_PICKAXE, 1));
        this.loot.add(create(Material.IRON_PICKAXE, 1));
        this.loot.add(create(Material.DIAMOND_PICKAXE, 1));
        this.loot.add(create(Material.DIAMOND_PICKAXE, 1));
        this.loot.add(create(Material.DIAMOND_PICKAXE, 1));
        this.loot.add(create(Material.APPLE, rndInt(1, 4)));
        this.loot.add(create(Material.IRON_BOOTS, 1));
        this.loot.add(create(Material.COOKED_CHICKEN, rndInt(1, 5)));
        this.loot.add(create(Material.CHAINMAIL_LEGGINGS, 1));
        this.loot.add(create(Material.COOKED_BEEF, rndInt(1, 5)));
        this.loot.add(create(Material.IRON_SWORD, 1));
        this.loot.add(create(Material.DIAMOND_CHESTPLATE, 1));
        this.loot.add(create(Material.CHAINMAIL_HELMET, 1));
        this.loot.add(create(Material.APPLE, rndInt(1, 4)));
        this.loot.add(create(Material.GOLDEN_CHESTPLATE, 1));
        this.loot.add(create(Material.IRON_CHESTPLATE, 1));
        this.loot.add(create(Material.BAKED_POTATO, rndInt(1, 5)));
        this.loot.add(create(Material.IRON_SWORD, 1));
        this.loot.add(create(Material.CHAINMAIL_BOOTS, 1));
        this.loot.add(create(Material.EXPERIENCE_BOTTLE, rndInt(1, 4)));
        this.loot.add(create(Material.BAKED_POTATO, rndInt(1, 5)));
        this.loot.add(create(Material.CHAINMAIL_LEGGINGS, 1));
        this.loot.add(create(Material.MELON, rndInt(1, 5)));
        this.loot.add(create(Material.STONE_SWORD, 1));
        this.loot.add(create(Material.IRON_LEGGINGS, 1));
        this.loot.add(create(Material.APPLE, rndInt(1, 4)));
        this.loot.add(create(Material.IRON_BOOTS, 1));
        this.loot.add(create(Material.FISHING_ROD, 1));
        this.loot.add(create(Material.COOKED_CHICKEN, rndInt(1, 5)));
        this.loot.add(create(Material.CHAINMAIL_LEGGINGS, 1));
        this.loot.add(create(Material.STONE, rndInt(1, 64)));
        this.loot.add(create(Material.COBBLESTONE, rndInt(1, 64)));   
        this.loot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.loot.add(create(Material.OAK_PLANKS, rndInt(1, 64)));
        this.loot.add(create(Material.BRICK, rndInt(1, 64)));
        this.loot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.loot.add(create(Material.STONE, rndInt(1, 64)));
        this.loot.add(create(Material.COBBLESTONE, rndInt(1, 64)));
        this.loot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.loot.add(create(Material.OAK_PLANKS, rndInt(1, 64)));
        this.loot.add(create(Material.BRICK, rndInt(1, 64)));
        this.loot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.loot.add(create(Material.STONE, rndInt(1, 64)));
        this.loot.add(create(Material.COBBLESTONE, rndInt(1, 64)));
        this.loot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.loot.add(create(Material.OAK_PLANKS, rndInt(1, 64)));
        this.loot.add(create(Material.BRICK, rndInt(1, 64)));
        this.loot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.loot.add(create(Material.STONE, rndInt(1, 64)));
        this.loot.add(create(Material.COBBLESTONE, rndInt(1, 64)));
        this.loot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.loot.add(create(Material.OAK_PLANKS, rndInt(1, 64)));
        this.loot.add(create(Material.BRICK, rndInt(1, 64)));
        this.loot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.loot.add(create(Material.COOKED_BEEF, rndInt(1, 5)));
        this.loot.add(create(Material.GOLDEN_BOOTS, 1));
        this.loot.add(create(Material.CHAINMAIL_HELMET, 1));
        this.loot.add(create(Material.APPLE, rndInt(1, 4)));
        this.loot.add(create(Material.IRON_HELMET, 1));
        this.loot.add(create(Material.GOLDEN_CHESTPLATE, 1));
        this.loot.add(create(Material.IRON_CHESTPLATE, 1));
        this.loot.add(create(Material.EXPERIENCE_BOTTLE, rndInt(1, 4)));
        this.loot.add(create(Material.BAKED_POTATO, rndInt(1, 5)));
        this.loot.add(create(Material.STONE_SWORD, 1));
        this.loot.add(create(Material.CHAINMAIL_BOOTS, 1));
        this.loot.add(create(Material.BAKED_POTATO, rndInt(1, 5)));
        this.loot.add(create(Material.CHAINMAIL_LEGGINGS, 1));
        this.loot.add(create(Material.MELON, rndInt(1, 5)));
        this.loot.add(create(Material.IRON_LEGGINGS, 1));
        this.loot.add(create(Material.APPLE, rndInt(1, 4)));
        this.loot.add(create(Material.COOKED_CHICKEN, rndInt(1, 5)));
        this.loot.add(create(Material.CHAINMAIL_LEGGINGS, 1));
        this.loot.add(create(Material.COOKED_BEEF, rndInt(1, 5)));
        this.loot.add(create(Material.IRON_SWORD, 1));
        this.loot.add(create(Material.DIAMOND_CHESTPLATE, 1));
        this.loot.add(create(Material.EXPERIENCE_BOTTLE, rndInt(1, 4)));
        this.loot.add(create(Material.FISHING_ROD, 1));
        this.loot.add(create(Material.APPLE, rndInt(1, 4)));
        this.loot.add(create(Material.GOLDEN_CHESTPLATE, 1));
        this.loot.add(create(Material.IRON_CHESTPLATE, 1));
        this.loot.add(create(Material.BAKED_POTATO, rndInt(1, 5)));
        this.loot.add(create(Material.GOLDEN_APPLE, 1));
        this.loot.add(create(Material.CHAINMAIL_BOOTS, 1));
        this.loot.add(create(Material.STONE, rndInt(1, 64)));
        this.loot.add(create(Material.COBBLESTONE, rndInt(1, 64)));
        this.loot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.loot.add(create(Material.OAK_PLANKS, rndInt(1, 64)));
        this.loot.add(create(Material.BRICK, rndInt(1, 64)));
        this.loot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.loot.add(create(Material.BAKED_POTATO, rndInt(1, 5)));
        this.loot.add(create(Material.CHAINMAIL_LEGGINGS, 1));
        this.loot.add(create(Material.MELON, rndInt(1, 5)));
        this.loot.add(create(Material.IRON_LEGGINGS, 1));
        this.loot.add(create(Material.APPLE, rndInt(1, 4)));
        this.loot.add(create(Material.IRON_BOOTS, 1));
        this.loot.add(create(Material.COOKED_CHICKEN, rndInt(1, 5)));
        this.loot.add(create(Material.CHAINMAIL_LEGGINGS, 1));
        this.loot.add(create(Material.COOKED_BEEF, rndInt(1, 5)));
        this.loot.add(create(Material.GOLDEN_BOOTS, 1));
        this.loot.add(create(Material.COBBLESTONE, rndInt(1, 64)));
        this.loot.add(create(Material.COBBLESTONE, rndInt(1, 64)));
        this.loot.add(create(Material.COBBLESTONE, rndInt(1, 64)));
        this.loot.add(create(Material.STONE, rndInt(1, 64)));
        this.loot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.loot.add(create(Material.OAK_PLANKS, rndInt(1, 64)));
        this.loot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.loot.add(create(Material.OAK_PLANKS, rndInt(1, 64)));
        this.loot.add(create(Material.BRICK, rndInt(1, 64)));
        this.loot.add(create(Material.BRICK, rndInt(1, 64)));
        this.loot.add(create(Material.BRICK, rndInt(1, 64)));
        this.loot.add(create(Material.COBBLESTONE, rndInt(1, 64)));
        this.loot.add(create(Material.COBBLESTONE, rndInt(1, 64)));
        this.loot.add(create(Material.COBBLESTONE, rndInt(1, 64)));
        this.loot.add(create(Material.STONE, rndInt(1, 64)));
        this.loot.add(create(Material.COBBLESTONE, rndInt(1, 64)));
        this.loot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.loot.add(create(Material.OAK_PLANKS, rndInt(1, 64)));
        this.loot.add(create(Material.BRICK, rndInt(1, 64)));
        this.loot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.loot.add(create(Material.OAK_PLANKS, rndInt(1, 64)));
        this.loot.add(create(Material.BRICK, rndInt(1, 64)));
        this.loot.add(create(Material.BRICK, rndInt(1, 64)));
        this.loot.add(create(Material.BRICK, rndInt(1, 64)));
        this.loot.add(create(Material.WATER_BUCKET, rndInt(1, 1)));
        this.loot.add(create(Material.WATER_BUCKET, rndInt(1, 1)));
        this.loot.add(create(Material.LAVA_BUCKET, rndInt(1, 1)));
        this.loot.add(create(Material.LAVA_BUCKET, rndInt(1, 1)));
        this.loot.add(create(Material.ENDER_PEARL, rndInt(1, 1)));
        this.loot.add(create(Material.ENDER_PEARL, rndInt(1, 1)));
        this.loot.add(create(Material.WATER_BUCKET, rndInt(1, 1)));
        this.loot.add(create(Material.WATER_BUCKET, rndInt(1, 1)));
        this.loot.add(create(Material.LAVA_BUCKET, rndInt(1, 1)));
        this.loot.add(create(Material.LAVA_BUCKET, rndInt(1, 1)));
        this.loot.add(create(Material.ENDER_PEARL, rndInt(1, 1)));
    }
    
    public void registerEpicLoot() {
    	// enchanted items
    	this.epicloot.add(createEnchanted(Material.CHAINMAIL_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.CHAINMAIL_CHESTPLATE, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.CHAINMAIL_LEGGINGS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.CHAINMAIL_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.IRON_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.IRON_CHESTPLATE, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.IRON_LEGGINGS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.IRON_BOOTS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.CHAINMAIL_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.CHAINMAIL_CHESTPLATE, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.CHAINMAIL_LEGGINGS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.CHAINMAIL_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.IRON_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.IRON_CHESTPLATE, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.IRON_LEGGINGS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.IRON_BOOTS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.IRON_SWORD, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.DIAMOND_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.DIAMOND_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.DIAMOND_CHESTPLATE, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.DIAMOND_CHESTPLATE, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.DIAMOND_LEGGINGS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.DIAMOND_LEGGINGS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.DIAMOND_BOOTS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.DIAMOND_BOOTS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.DIAMOND_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.DIAMOND_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.DIAMOND_CHESTPLATE, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.DIAMOND_CHESTPLATE, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.DIAMOND_LEGGINGS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.DIAMOND_LEGGINGS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.DIAMOND_BOOTS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.DIAMOND_BOOTS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.IRON_SWORD, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.CHAINMAIL_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.CHAINMAIL_CHESTPLATE, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.CHAINMAIL_LEGGINGS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.CHAINMAIL_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.IRON_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.IRON_CHESTPLATE, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.IRON_LEGGINGS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.IRON_BOOTS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.CHAINMAIL_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.CHAINMAIL_CHESTPLATE, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.CHAINMAIL_LEGGINGS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.CHAINMAIL_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.IRON_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.IRON_CHESTPLATE, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.IRON_LEGGINGS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.IRON_BOOTS, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.IRON_SWORD, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	this.epicloot.add(createEnchanted(Material.IRON_SWORD, Enchantment.PROTECTION_ENVIRONMENTAL, 1));
    	
    	// potions
    	this.epicloot.add(createPotion(Material.SPLASH_POTION, PotionType.REGEN, 1, false, true));
    	this.epicloot.add(createPotion(Material.SPLASH_POTION, PotionType.INSTANT_HEAL, 1, false, true));
    	this.epicloot.add(createPotion(Material.SPLASH_POTION, PotionType.SLOWNESS, 1, false, false));
    	this.epicloot.add(createPotion(Material.SPLASH_POTION, PotionType.WEAKNESS, 1, false, false));
    	this.epicloot.add(createPotion(Material.SPLASH_POTION, PotionType.POISON, 1, false, false));
    	this.epicloot.add(createPotion(Material.SPLASH_POTION, PotionType.REGEN, 1, false, true));
    	this.epicloot.add(createPotion(Material.SPLASH_POTION, PotionType.INSTANT_HEAL, 2, false, true));
    	this.epicloot.add(createPotion(Material.SPLASH_POTION, PotionType.INSTANT_HEAL, 5, false, true));
    	this.epicloot.add(createPotion(Material.SPLASH_POTION, PotionType.INSTANT_HEAL, 2, false, true));
    	this.epicloot.add(createPotion(Material.SPLASH_POTION, PotionType.INSTANT_HEAL, 5, false, true));
    	
    	// regular items
        this.epicloot.add(create(Material.BAKED_POTATO, rndInt(1, 10)));
        this.epicloot.add(create(Material.GOLDEN_APPLE, 1));
        this.epicloot.add(create(Material.GOLDEN_APPLE, 1));
        this.epicloot.add(create(Material.GOLDEN_APPLE, 1));
        this.epicloot.add(create(Material.GOLDEN_APPLE, 1));
        this.epicloot.add(create(Material.STONE_SWORD, 1));
        this.epicloot.add(create(Material.FISHING_ROD, 1));
        this.epicloot.add(create(Material.EXPERIENCE_BOTTLE, rndInt(1, 4)));
        this.epicloot.add(create(Material.DIAMOND_CHESTPLATE, 1));
        this.epicloot.add(create(Material.DIAMOND, rndInt(1, 8)));
        this.epicloot.add(create(Material.IRON_INGOT, rndInt(1, 8)));
        this.epicloot.add(create(Material.IRON_INGOT, rndInt(1, 8)));
        this.epicloot.add(create(Material.BAKED_POTATO, rndInt(1, 5)));
        this.epicloot.add(create(Material.MELON, rndInt(1, 5)));
        this.epicloot.add(create(Material.TNT, rndInt(1, 8)));
        this.epicloot.add(create(Material.TNT, rndInt(1, 8)));
        this.epicloot.add(create(Material.TNT, rndInt(1, 8)));
        this.epicloot.add(create(Material.TNT, rndInt(1, 8)));
        this.epicloot.add(create(Material.TNT, rndInt(1, 8)));
        this.epicloot.add(create(Material.FLINT_AND_STEEL, rndInt(1, 1)));
        this.epicloot.add(create(Material.TNT, rndInt(1, 8)));
        this.epicloot.add(create(Material.FLINT_AND_STEEL, rndInt(1, 1)));
        this.epicloot.add(create(Material.FLINT_AND_STEEL, rndInt(1, 1)));
        this.epicloot.add(create(Material.FLINT_AND_STEEL, rndInt(1, 1)));
        this.epicloot.add(create(Material.IRON_LEGGINGS, 1));
        this.epicloot.add(create(Material.APPLE, rndInt(1, 4)));
        this.epicloot.add(create(Material.IRON_BOOTS, 1));
        this.epicloot.add(create(Material.COOKED_CHICKEN, rndInt(1, 5)));
        this.epicloot.add(create(Material.COOKED_BEEF, rndInt(1, 5)));
        this.epicloot.add(create(Material.GOLDEN_BOOTS, 1));
        this.epicloot.add(create(Material.IRON_SWORD, 1));
        this.epicloot.add(create(Material.APPLE, rndInt(1, 4)));
        this.epicloot.add(create(Material.IRON_HELMET, 1));
        this.epicloot.add(create(Material.GOLDEN_CHESTPLATE, 1));
        this.epicloot.add(create(Material.BAKED_POTATO, rndInt(1, 5)));
        this.epicloot.add(create(Material.BAKED_POTATO, rndInt(1, 5)));
        this.epicloot.add(create(Material.CHAINMAIL_LEGGINGS, 1));
        this.epicloot.add(create(Material.EXPERIENCE_BOTTLE, rndInt(1, 4)));
        this.epicloot.add(create(Material.EXPERIENCE_BOTTLE, rndInt(1, 4)));
        this.epicloot.add(create(Material.EXPERIENCE_BOTTLE, rndInt(1, 4)));
        this.epicloot.add(create(Material.COOKED_CHICKEN, rndInt(1, 5)));
        this.epicloot.add(create(Material.CHAINMAIL_LEGGINGS, 1));
        this.epicloot.add(create(Material.COOKED_BEEF, rndInt(1, 5)));
        this.epicloot.add(create(Material.IRON_SWORD, 1));
        this.epicloot.add(create(Material.FISHING_ROD, 1));
        this.epicloot.add(create(Material.CHAINMAIL_HELMET, 1));
        this.epicloot.add(create(Material.APPLE, rndInt(1, 4)));
        this.epicloot.add(create(Material.IRON_HELMET, 1));
        this.epicloot.add(create(Material.GOLDEN_CHESTPLATE, 1));
        this.epicloot.add(create(Material.STONE_AXE, 1));
        this.epicloot.add(create(Material.IRON_CHESTPLATE, 1));
        this.epicloot.add(create(Material.BAKED_POTATO, rndInt(1, 5)));
        this.epicloot.add(create(Material.IRON_SWORD, 1));
        this.epicloot.add(create(Material.CHAINMAIL_BOOTS, 1));
        this.epicloot.add(create(Material.EXPERIENCE_BOTTLE, rndInt(1, 4)));
        this.epicloot.add(create(Material.BAKED_POTATO, rndInt(1, 5)));
        this.epicloot.add(create(Material.STONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.COBBLESTONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.OAK_PLANKS, rndInt(1, 64)));
        this.epicloot.add(create(Material.BRICK, rndInt(1, 64)));
        this.epicloot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.STONE_SWORD, 1));
        this.epicloot.add(create(Material.MELON, rndInt(1, 5)));
        this.epicloot.add(create(Material.IRON_LEGGINGS, 1));
        this.epicloot.add(create(Material.APPLE, rndInt(1, 4)));
        this.epicloot.add(create(Material.IRON_BOOTS, 1));
        this.epicloot.add(create(Material.DIAMOND_CHESTPLATE, 1));
        this.epicloot.add(create(Material.COOKED_CHICKEN, rndInt(1, 5)));
        this.epicloot.add(create(Material.CHAINMAIL_LEGGINGS, 1));
        this.epicloot.add(create(Material.COOKED_BEEF, rndInt(1, 5)));
        this.epicloot.add(create(Material.GOLDEN_BOOTS, 1));
        this.epicloot.add(create(Material.IRON_SWORD, 1));
        this.epicloot.add(create(Material.APPLE, rndInt(1, 4)));
        this.epicloot.add(create(Material.IRON_HELMET, 1));
        this.epicloot.add(create(Material.GOLDEN_CHESTPLATE, 1));
        this.epicloot.add(create(Material.IRON_CHESTPLATE, 1));
        this.epicloot.add(create(Material.BAKED_POTATO, rndInt(1, 5)));
        this.epicloot.add(create(Material.GOLDEN_APPLE, 1));
        this.epicloot.add(create(Material.CHAINMAIL_BOOTS, 1));
        this.epicloot.add(create(Material.STONE_SWORD, 1));
        this.epicloot.add(create(Material.COBWEB, rndInt(1, 4)));
        this.epicloot.add(create(Material.EXPERIENCE_BOTTLE, rndInt(1, 4)));
        this.epicloot.add(create(Material.BAKED_POTATO, rndInt(1, 5)));
        this.epicloot.add(create(Material.CHAINMAIL_LEGGINGS, 1));
        this.epicloot.add(create(Material.EXPERIENCE_BOTTLE, 5));
        this.epicloot.add(create(Material.EXPERIENCE_BOTTLE, 5));
        this.epicloot.add(create(Material.EXPERIENCE_BOTTLE, 7));
        this.epicloot.add(create(Material.EXPERIENCE_BOTTLE, 7));
        this.epicloot.add(create(Material.EXPERIENCE_BOTTLE, 16));
        this.epicloot.add(create(Material.EXPERIENCE_BOTTLE, 11));
        this.epicloot.add(create(Material.MELON, rndInt(1, 5)));
        this.epicloot.add(create(Material.APPLE, rndInt(1, 4)));
        this.epicloot.add(create(Material.COOKED_CHICKEN, rndInt(1, 5)));
        this.epicloot.add(create(Material.CHAINMAIL_LEGGINGS, 1));
        this.epicloot.add(create(Material.COOKED_BEEF, rndInt(1, 5)));
        this.epicloot.add(create(Material.GOLDEN_BOOTS, 1));
        this.epicloot.add(create(Material.CHAINMAIL_HELMET, 1));
        this.epicloot.add(create(Material.APPLE, rndInt(1, 4)));
        this.epicloot.add(create(Material.GOLDEN_CHESTPLATE, 1));
        this.epicloot.add(create(Material.STONE_SWORD, 1));
        this.epicloot.add(create(Material.STONE_AXE, 1));
        this.epicloot.add(create(Material.FISHING_ROD, 1));
        this.epicloot.add(create(Material.IRON_CHESTPLATE, 1));
        this.epicloot.add(create(Material.BAKED_POTATO, rndInt(1, 5)));
        this.epicloot.add(create(Material.GOLDEN_APPLE, 1));
        this.epicloot.add(create(Material.STICK, rndInt(1, 3)));
        this.epicloot.add(create(Material.BAKED_POTATO, rndInt(1, 5)));
        this.epicloot.add(create(Material.CHAINMAIL_LEGGINGS, 1));
        this.epicloot.add(create(Material.MELON, rndInt(1, 5)));
        this.epicloot.add(create(Material.IRON_LEGGINGS, 1));
        this.epicloot.add(create(Material.GOLDEN_PICKAXE, 1));
        this.epicloot.add(create(Material.GOLDEN_PICKAXE, 1));
        this.epicloot.add(create(Material.GOLDEN_PICKAXE, 1));
        this.epicloot.add(create(Material.IRON_PICKAXE, 1));
        this.epicloot.add(create(Material.IRON_PICKAXE, 1));
        this.epicloot.add(create(Material.IRON_PICKAXE, 1));
        this.epicloot.add(create(Material.DIAMOND_PICKAXE, 1));
        this.epicloot.add(create(Material.DIAMOND_PICKAXE, 1));
        this.epicloot.add(create(Material.DIAMOND_PICKAXE, 1));
        this.epicloot.add(create(Material.APPLE, rndInt(1, 4)));
        this.epicloot.add(create(Material.IRON_BOOTS, 1));
        this.epicloot.add(create(Material.COOKED_CHICKEN, rndInt(1, 5)));
        this.epicloot.add(create(Material.CHAINMAIL_LEGGINGS, 1));
        this.epicloot.add(create(Material.COOKED_BEEF, rndInt(1, 5)));
        this.epicloot.add(create(Material.IRON_SWORD, 1));
        this.epicloot.add(create(Material.DIAMOND_CHESTPLATE, 1));
        this.epicloot.add(create(Material.CHAINMAIL_HELMET, 1));
        this.epicloot.add(create(Material.APPLE, rndInt(1, 4)));
        this.epicloot.add(create(Material.GOLDEN_CHESTPLATE, 1));
        this.epicloot.add(create(Material.IRON_CHESTPLATE, 1));
        this.epicloot.add(create(Material.BAKED_POTATO, rndInt(1, 5)));
        this.epicloot.add(create(Material.IRON_SWORD, 1));
        this.epicloot.add(create(Material.CHAINMAIL_BOOTS, 1));
        this.epicloot.add(create(Material.EXPERIENCE_BOTTLE, rndInt(1, 4)));
        this.epicloot.add(create(Material.BAKED_POTATO, rndInt(1, 5)));
        this.epicloot.add(create(Material.CHAINMAIL_LEGGINGS, 1));
        this.epicloot.add(create(Material.MELON, rndInt(1, 5)));
        this.epicloot.add(create(Material.STONE_SWORD, 1));
        this.epicloot.add(create(Material.IRON_LEGGINGS, 1));
        this.epicloot.add(create(Material.APPLE, rndInt(1, 4)));
        this.epicloot.add(create(Material.IRON_BOOTS, 1));
        this.epicloot.add(create(Material.FISHING_ROD, 1));
        this.epicloot.add(create(Material.COOKED_CHICKEN, rndInt(1, 5)));
        this.epicloot.add(create(Material.CHAINMAIL_LEGGINGS, 1));
        this.epicloot.add(create(Material.STONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.COBBLESTONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.OAK_PLANKS, rndInt(1, 64)));
        this.epicloot.add(create(Material.BRICK, rndInt(1, 64)));
        this.epicloot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.STONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.COBBLESTONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.OAK_PLANKS, rndInt(1, 64)));
        this.epicloot.add(create(Material.BRICK, rndInt(1, 64)));
        this.epicloot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.STONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.COBBLESTONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.OAK_PLANKS, rndInt(1, 64)));
        this.epicloot.add(create(Material.BRICK, rndInt(1, 64)));
        this.epicloot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.STONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.COBBLESTONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.OAK_PLANKS, rndInt(1, 64)));
        this.epicloot.add(create(Material.BRICK, rndInt(1, 64)));
        this.epicloot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.COOKED_BEEF, rndInt(1, 5)));
        this.epicloot.add(create(Material.GOLDEN_BOOTS, 1));
        this.epicloot.add(create(Material.CHAINMAIL_HELMET, 1));
        this.epicloot.add(create(Material.APPLE, rndInt(1, 4)));
        this.epicloot.add(create(Material.IRON_HELMET, 1));
        this.epicloot.add(create(Material.GOLDEN_CHESTPLATE, 1));
        this.epicloot.add(create(Material.IRON_CHESTPLATE, 1));
        this.epicloot.add(create(Material.EXPERIENCE_BOTTLE, rndInt(1, 4)));
        this.epicloot.add(create(Material.BAKED_POTATO, rndInt(1, 5)));
        this.epicloot.add(create(Material.STONE_SWORD, 1));
        this.epicloot.add(create(Material.CHAINMAIL_BOOTS, 1));
        this.epicloot.add(create(Material.BAKED_POTATO, rndInt(1, 5)));
        this.epicloot.add(create(Material.CHAINMAIL_LEGGINGS, 1));
        this.epicloot.add(create(Material.MELON, rndInt(1, 5)));
        this.epicloot.add(create(Material.IRON_LEGGINGS, 1));
        this.epicloot.add(create(Material.APPLE, rndInt(1, 4)));
        this.epicloot.add(create(Material.COOKED_CHICKEN, rndInt(1, 5)));
        this.epicloot.add(create(Material.CHAINMAIL_LEGGINGS, 1));
        this.epicloot.add(create(Material.COOKED_BEEF, rndInt(1, 5)));
        this.epicloot.add(create(Material.IRON_SWORD, 1));
        this.epicloot.add(create(Material.DIAMOND_CHESTPLATE, 1));
        this.epicloot.add(create(Material.EXPERIENCE_BOTTLE, rndInt(1, 4)));
        this.epicloot.add(create(Material.FISHING_ROD, 1));
        this.epicloot.add(create(Material.APPLE, rndInt(1, 4)));
        this.epicloot.add(create(Material.GOLDEN_CHESTPLATE, 1));
        this.epicloot.add(create(Material.IRON_CHESTPLATE, 1));
        this.epicloot.add(create(Material.BAKED_POTATO, rndInt(1, 5)));
        this.epicloot.add(create(Material.GOLDEN_APPLE, 1));
        this.epicloot.add(create(Material.CHAINMAIL_BOOTS, 1));
        this.epicloot.add(create(Material.STONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.COBBLESTONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.OAK_PLANKS, rndInt(1, 64)));
        this.epicloot.add(create(Material.BRICK, rndInt(1, 64)));
        this.epicloot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.BAKED_POTATO, rndInt(1, 5)));
        this.epicloot.add(create(Material.CHAINMAIL_LEGGINGS, 1));
        this.epicloot.add(create(Material.MELON, rndInt(1, 5)));
        this.epicloot.add(create(Material.IRON_LEGGINGS, 1));
        this.epicloot.add(create(Material.APPLE, rndInt(1, 4)));
        this.epicloot.add(create(Material.IRON_BOOTS, 1));
        this.epicloot.add(create(Material.COOKED_CHICKEN, rndInt(1, 5)));
        this.epicloot.add(create(Material.CHAINMAIL_LEGGINGS, 1));
        this.epicloot.add(create(Material.COOKED_BEEF, rndInt(1, 5)));
        this.epicloot.add(create(Material.SNOWBALL, 16));
        this.epicloot.add(create(Material.SNOWBALL, 7));
        this.epicloot.add(create(Material.SNOWBALL, 5));
        this.epicloot.add(create(Material.SNOWBALL, 5));
        this.epicloot.add(create(Material.SNOWBALL, 3));
        this.epicloot.add(create(Material.SNOWBALL, 3));
        this.epicloot.add(create(Material.SNOWBALL, 1));
        this.epicloot.add(create(Material.SNOWBALL, 1));
        this.epicloot.add(create(Material.SNOWBALL, 1));
        this.epicloot.add(create(Material.EGG, 16));
        this.epicloot.add(create(Material.EGG, 7));
        this.epicloot.add(create(Material.EGG, 5));
        this.epicloot.add(create(Material.EGG, 5));
        this.epicloot.add(create(Material.EGG, 3));
        this.epicloot.add(create(Material.EGG, 3));
        this.epicloot.add(create(Material.EGG, 1));
        this.epicloot.add(create(Material.EGG, 1));
        this.epicloot.add(create(Material.EGG, 1));
        this.epicloot.add(create(Material.ENDER_PEARL, 1));
        this.epicloot.add(create(Material.GOLDEN_BOOTS, 1));
        this.epicloot.add(create(Material.COBBLESTONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.COBBLESTONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.COBBLESTONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.STONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.OAK_PLANKS, rndInt(1, 64)));
        this.epicloot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.OAK_PLANKS, rndInt(1, 64)));
        this.epicloot.add(create(Material.BRICK, rndInt(1, 64)));
        this.epicloot.add(create(Material.BRICK, rndInt(1, 64)));
        this.epicloot.add(create(Material.BRICK, rndInt(1, 64)));
        this.epicloot.add(create(Material.COBBLESTONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.COBBLESTONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.COBBLESTONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.STONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.COBBLESTONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.OAK_PLANKS, rndInt(1, 64)));
        this.epicloot.add(create(Material.BRICK, rndInt(1, 64)));
        this.epicloot.add(create(Material.SANDSTONE, rndInt(1, 64)));
        this.epicloot.add(create(Material.OAK_PLANKS, rndInt(1, 64)));
        this.epicloot.add(create(Material.BRICK, rndInt(1, 64)));
        this.epicloot.add(create(Material.BRICK, rndInt(1, 64)));
        this.epicloot.add(create(Material.BRICK, rndInt(1, 64)));
        this.epicloot.add(create(Material.WATER_BUCKET, rndInt(1, 1)));
        this.epicloot.add(create(Material.WATER_BUCKET, rndInt(1, 1)));
        this.epicloot.add(create(Material.LAVA_BUCKET, rndInt(1, 1)));
        this.epicloot.add(create(Material.LAVA_BUCKET, rndInt(1, 1)));
        this.epicloot.add(create(Material.ENDER_PEARL, rndInt(1, 1)));
        this.epicloot.add(create(Material.ENDER_PEARL, rndInt(1, 1)));
        this.epicloot.add(create(Material.WATER_BUCKET, rndInt(1, 1)));
        this.epicloot.add(create(Material.WATER_BUCKET, rndInt(1, 1)));
        this.epicloot.add(create(Material.LAVA_BUCKET, rndInt(1, 1)));
        this.epicloot.add(create(Material.LAVA_BUCKET, rndInt(1, 1)));
        this.epicloot.add(create(Material.ENDER_PEARL, rndInt(1, 1)));

    }
    public static void clear(){
    	chests.clear();
    }
}
